#!/usr/bin/env bash
set -euo pipefail

# =============================================================================
# lavalink-ops — One-Click Setup
# Generates secrets, creates .env, syncs config, and prepares data directories.
# =============================================================================

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="$SCRIPT_DIR/.env"
ENV_EXAMPLE="$SCRIPT_DIR/.env.example"
CONFIG_FILE="$SCRIPT_DIR/config/application.yml"

# --- Helpers ---

generate_secret() {
    # Generate a cryptographically random alphanumeric string
    local length="${1:-32}"
    head -c 256 /dev/urandom | LC_ALL=C tr -dc 'a-zA-Z0-9' | head -c "$length"
}

generate_password() {
    # Shorter, human-friendly password for things users might type
    local length="${1:-16}"
    head -c 256 /dev/urandom | LC_ALL=C tr -dc 'a-zA-Z0-9' | head -c "$length"
}

log() { echo "  $1"; }

# --- Pre-flight ---

if [ ! -f "$ENV_EXAMPLE" ]; then
    echo "ERROR: $ENV_EXAMPLE not found. Are you in the lavalink-ops directory?"
    exit 1
fi

if [ ! -f "$CONFIG_FILE" ]; then
    echo "ERROR: $CONFIG_FILE not found."
    exit 1
fi

echo ""
echo "  lavalink-ops setup"
echo "  ==================="
echo ""

# --- Generate or preserve .env ---

if [ -f "$ENV_FILE" ]; then
    echo "  .env already exists."
    read -rp "  Overwrite with fresh secrets? [y/N] " answer
    if [[ ! "$answer" =~ ^[Yy]$ ]]; then
        log "Keeping existing .env"
        log ""
        SKIP_ENV=true
    else
        SKIP_ENV=false
    fi
else
    SKIP_ENV=false
fi

if [ "$SKIP_ENV" = false ]; then
    LAVALINK_PASSWORD="$(generate_password 20)"
    CIPHER_API_TOKEN="$(generate_secret 32)"
    ADMIN_PASSWORD="$(generate_password 16)"
    ADMIN_SECRET_KEY="$(generate_secret 48)"

    cat > "$ENV_FILE" <<EOF
# =============================================================================
# lavalink-ops — Environment Configuration
# Generated by setup.sh on $(date -u +"%Y-%m-%d %H:%M:%S UTC")
# =============================================================================

# --- Lavalink ---
LAVALINK_PASSWORD=${LAVALINK_PASSWORD}
LAVALINK_PORT=2333
LAVALINK_JAVA_OPTS=-Xmx512M
LAVALINK_CONTAINER_NAME=lavalink

# --- yt-cipher ---
CIPHER_API_TOKEN=${CIPHER_API_TOKEN}

# --- Admin Panel ---
ADMIN_PASSWORD=${ADMIN_PASSWORD}
ADMIN_SECRET_KEY=${ADMIN_SECRET_KEY}
ADMIN_PORT=8080

# --- PoToken Refresh ---
POT_REFRESH_ENABLED=true
POT_REFRESH_INTERVAL_HOURS=6
EOF

    log "Generated .env with fresh secrets"

    # --- Sync secrets into application.yml ---
    # Replace the lavalink server password
    sed -i "s|password: \"youshallnotpass\"|password: \"${LAVALINK_PASSWORD}\"|g" "$CONFIG_FILE"
    # Also handle unquoted form
    sed -i "s|password: youshallnotpass|password: \"${LAVALINK_PASSWORD}\"|g" "$CONFIG_FILE"

    # Replace the cipher token
    sed -i "s|password: \"change-me-cipher-token\"|password: \"${CIPHER_API_TOKEN}\"|g" "$CONFIG_FILE"
    sed -i "s|password: change-me-cipher-token|password: \"${CIPHER_API_TOKEN}\"|g" "$CONFIG_FILE"

    log "Synced secrets into application.yml"

    echo ""
    echo "  Generated credentials:"
    echo "  ----------------------"
    echo "  Admin password:    ${ADMIN_PASSWORD}"
    echo "  Lavalink password: ${LAVALINK_PASSWORD}"
    echo ""
    echo "  Save these! They're also stored in .env"
    echo ""
fi

# --- Create data directories ---

mkdir -p "$SCRIPT_DIR/data/lavalink/plugins"
mkdir -p "$SCRIPT_DIR/data/lavalink/logs"
mkdir -p "$SCRIPT_DIR/data/admin"
log "Created data directories"

echo ""
echo "  Setup complete! Start the stack with:"
echo ""
echo "    docker compose up --build -d"
echo ""
echo "  Then visit http://localhost:8080"
echo ""
